export const INPUT = 'text'
export const PASSWORD = 'password'
export const EMAIL = 'email'
export const TEXTAREA = 'textarea'
export const SELECT = 'select'
export const CHECKBOX = 'checkbox'
export const RADIO = 'radio'
